title: Kim Shellenberger # your name (or website title) here
logo: "/images/dashboard sample.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Skills  
<br><br>
Data Analysis & Visualization
<br><br> 
Statistical Programming & Predictive Modeling
<br><br>
Risk Adjustment & Clinical Data
<br><br>
Spatial Analysis Tableau & GIS Dashboards
<br><br>
GIS Web Maps & Field Apps
<br><br>
Program & Project Management
<br><br>
Photogrammetry
<br><br>
LiDAR Processing 
<br><br>

  
  <a href="https://www.linkedin.com/in/KimShellenberger/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

